# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/plensing/git/throughput

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/plensing/git/throughput

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/plensing/git/throughput/CMakeFiles /Users/plensing/git/throughput/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/plensing/git/throughput/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named throughput

# Build rule for target.
throughput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 throughput
.PHONY : throughput

# fast build rule for target.
throughput/fast:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/build
.PHONY : throughput/fast

threadsafe_blocking_connection.o: threadsafe_blocking_connection.cc.o
.PHONY : threadsafe_blocking_connection.o

# target to build an object file
threadsafe_blocking_connection.cc.o:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/threadsafe_blocking_connection.cc.o
.PHONY : threadsafe_blocking_connection.cc.o

threadsafe_blocking_connection.i: threadsafe_blocking_connection.cc.i
.PHONY : threadsafe_blocking_connection.i

# target to preprocess a source file
threadsafe_blocking_connection.cc.i:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/threadsafe_blocking_connection.cc.i
.PHONY : threadsafe_blocking_connection.cc.i

threadsafe_blocking_connection.s: threadsafe_blocking_connection.cc.s
.PHONY : threadsafe_blocking_connection.s

# target to generate assembly for a file
threadsafe_blocking_connection.cc.s:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/threadsafe_blocking_connection.cc.s
.PHONY : threadsafe_blocking_connection.cc.s

throughput.o: throughput.cc.o
.PHONY : throughput.o

# target to build an object file
throughput.cc.o:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/throughput.cc.o
.PHONY : throughput.cc.o

throughput.i: throughput.cc.i
.PHONY : throughput.i

# target to preprocess a source file
throughput.cc.i:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/throughput.cc.i
.PHONY : throughput.cc.i

throughput.s: throughput.cc.s
.PHONY : throughput.s

# target to generate assembly for a file
throughput.cc.s:
	$(MAKE) -f CMakeFiles/throughput.dir/build.make CMakeFiles/throughput.dir/throughput.cc.s
.PHONY : throughput.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... throughput"
	@echo "... threadsafe_blocking_connection.o"
	@echo "... threadsafe_blocking_connection.i"
	@echo "... threadsafe_blocking_connection.s"
	@echo "... throughput.o"
	@echo "... throughput.i"
	@echo "... throughput.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

